### ISSUE TITLE
Glibc dependency mismatch

### ISSUE THREAD

**Issue by damondine** [gwittchen/lambda-ocr#4]
I'm getting a package dependency mismatch with the glibc version when running the build.sh:

```
Error: Package: glibc-2.17-196.172.amzn1.i686 (amzn-updates)
           Requires: glibc-common = 2.17-196.172.amzn1
           Installed: glibc-common-2.17-260.175.amzn1.x86_64 (@amzn-updates/latest)
               glibc-common = 2.17-260.175.amzn1
           Available: glibc-common-2.17-157.169.amzn1.x86_64 (amzn-main)
               glibc-common = 2.17-157.169.amzn1
           Available: glibc-common-2.17-157.170.amzn1.x86_64 (amzn-updates)
               glibc-common = 2.17-157.170.amzn1
           Available: glibc-common-2.17-196.172.amzn1.x86_64 (amzn-updates)
               glibc-common = 2.17-196.172.amzn1
```
Thanks for your help!

**Comment by gwittchen** [comment]
Hello, thanks for your feedback?
Let me ask you a few questions:
Did you checkout the latest version of the code?
Are you running docker on Mac or Linux?

It could be related to yum cache you could try to update the dockerfile to the following command
```bash
## install dependencies
RUN yum -y clean expire-cache && yum -y makecache fast && yum -y update && yum -y install tar xz yum-utils gcc gcc-c++ make autoconf aclocal automake libtool findutils \
libjpeg-devel libpng-devel libtiff-devel zlib-devel \
libzip-devel freetype-devel lcms2-devel libwebp-devel \
tcl-devel tk-devel wget tar diffutils autoconf automake \
libjpeg8-devel libtiff5-devel zlib1g-devel zip
```

**Comment by damondine** [comment]
Hey, thanks for the quick reply, I'm on the latest version of the code, running docker version 2.0.0.0 on Mac.

Adding the clean expire cache didn't work immediately, but I added  ```clean expire-cache```
and removed installing ```yum-utils``` which worked for me now. I'm guessing it used yum-utils from cache as it already downloaded them from running previously, and just used ```glibc-common = 2.17-260.175.amzn1``` instead.

Thanks for your help, sorry i'm not as familiar in Python!

**Comment by gwittchen** [comment]
Thanks for the feedback, I will test and consider removing the yum-utils.

**Comment by vegarsti** [comment]
FWIW, I also had to remove `yum-utils`, thanks.
