### ISSUE TITLE
Docker build fails in ./build.sh

### ISSUE THREAD

**Issue by uriya2** [gwittchen/lambda-ocr#6]
hi,

I'm at the  "./build.sh" step and it keeps failing, I've separated the lines and saw the issue is with installing "yum-utils", any idea how to solve this?

build.sh output:
`
(tessenv) ➜  tesseract-layer git:(master) ✗ ./build.sh
+ set -e
+ libarray=(/usr/local/lib/libtesseract.so.4 /usr/local/lib/liblept.so.5 /usr/lib64/librt.so /usr/lib64/libz.so /usr/lib64/libm.so /usr/lib64/libpng12.so.0 /usr/lib64/libjpeg.so.62 /usr/lib64/libtiff.so.5 /usr/lib64/libpthread.so /usr/lib64/libstdc++.so.6 /usr/lib64/libjbig.so.2.0 /usr/lib64/libwebp.so.4)
+ pythondeps=(tesserocr.cpython-36m-x86_64-linux-gnu.so pytesseract-0.2.5.dist-info pytesseract Pillow-5.4.0.dist-info PIL Cython Cython-0.29.1.dist-info cython.py pyximport)
+ binaries=(/var/task/python/bin/cythonize /var/task/python/bin/cython /var/task/python/bin/cygdb)
+ LAMBDA_DIR=layer
+ rm -rf layer
+ mkdir -p layer/python/bin
+ mkdir -p layer/lib layer/bin layer/data
+ docker build -t tessleract-builder -f Dockerfile .
Sending build context to Docker daemon  10.75kB
Step 1/25 : FROM lambci/lambda:build-python3.6
 ---> d5324f05ff0e
Step 2/25 : ENV LEPTONICA_VERSION=leptonica-1.76.0
 ---> Using cache
 ---> ab9e4ac9bdf6
Step 3/25 : ENV TESSERACT_VERSION=4.0.0
 ---> Using cache
 ---> 39a9638e122e
Step 4/25 : ENV PYTHON_VERSION=3.6.1
 ---> Using cache
 ---> b9afaf11258c
Step 5/25 : RUN yum -y update && yum makecache fast && yum -y install tar xz yum-utils gcc gcc-c++ make autoconf aclocal automake libtool findutils libjpeg-devel libpng-devel libtiff-devel zlib-devel libzip-devel freetype-devel lcms2-devel libwebp-devel tcl-devel tk-devel wget tar diffutils autoconf automake libjpeg8-devel libtiff5-devel zlib1g-devel zip
 ---> Running in 9657f2b0a4e8
Loaded plugins: ovl
No packages marked for update
Loaded plugins: ovl
Metadata Cache Created
Loaded plugins: ovl
Package 2:tar-1.26-31.22.amzn1.x86_64 already installed and latest version
Package xz-5.1.2-12alpha.12.amzn1.x86_64 already installed and latest version
Package gcc-4.8.3-3.20.amzn1.noarch already installed and latest version
Package gcc-c++-4.8.3-3.20.amzn1.noarch already installed and latest version
Package 1:make-3.82-21.10.amzn1.x86_64 already installed and latest version
Package autoconf-2.69-11.9.amzn1.noarch already installed and latest version
No package aclocal available.
Package automake-1.13.4-3.15.amzn1.noarch already installed and latest version
Package libtool-2.4.2-20.4.8.3.31.amzn1.x86_64 already installed and latest version
Package 1:findutils-4.4.2-6.9.amzn1.x86_64 already installed and latest version
Package libjpeg-turbo-devel-1.2.90-5.14.amzn1.x86_64 already installed and latest version
Package 2:libpng-devel-1.2.49-2.14.amzn1.x86_64 already installed and latest version
Package libtiff-devel-4.0.3-27.29.amzn1.x86_64 already installed and latest version
Package zlib-devel-1.2.8-7.18.amzn1.x86_64 already installed and latest version
Package freetype-devel-2.3.11-15.14.amzn1.x86_64 already installed and latest version
Package lcms2-devel-2.6-2.5.amzn1.x86_64 already installed and latest version
No package tk-devel available.
Package 2:tar-1.26-31.22.amzn1.x86_64 already installed and latest version
Package diffutils-3.3-4.15.amzn1.x86_64 already installed and latest version
Package autoconf-2.69-11.9.amzn1.noarch already installed and latest version
Package automake-1.13.4-3.15.amzn1.noarch already installed and latest version
No package libjpeg8-devel available.
No package libtiff5-devel available.
No package zlib1g-devel available.
Package zip-3.0-1.10.amzn1.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package libwebp-devel.x86_64 0:0.3.0-3.5.amzn1 will be installed
--> Processing Dependency: libwebp(x86-64) = 0.3.0-3.5.amzn1 for package: libwebp-devel-0.3.0-3.5.amzn1.x86_64
--> Processing Dependency: libwebp.so.4()(64bit) for package: libwebp-devel-0.3.0-3.5.amzn1.x86_64
--> Processing Dependency: libwebpmux.so.0()(64bit) for package: libwebp-devel-0.3.0-3.5.amzn1.x86_64
---> Package libzip-devel.x86_64 0:0.10.1-1.3.amzn1 will be installed
--> Processing Dependency: libzip = 0.10.1-1.3.amzn1 for package: libzip-devel-0.10.1-1.3.amzn1.x86_64
--> Processing Dependency: libzip.so.2()(64bit) for package: libzip-devel-0.10.1-1.3.amzn1.x86_64
---> Package tcl-devel.x86_64 1:8.5.7-6.9.amzn1 will be installed
--> Processing Dependency: tcl = 1:8.5.7-6.9.amzn1 for package: 1:tcl-devel-8.5.7-6.9.amzn1.x86_64
--> Processing Dependency: libtcl8.5.so()(64bit) for package: 1:tcl-devel-8.5.7-6.9.amzn1.x86_64
---> Package wget.x86_64 0:1.18-3.27.amzn1 will be installed
---> Package yum-utils.noarch 0:1.1.31-40.29.amzn1 will be installed
--> Processing Dependency: libxml2-python27 for package: yum-utils-1.1.31-40.29.amzn1.noarch
--> Processing Dependency: python27-kitchen for package: yum-utils-1.1.31-40.29.amzn1.noarch
--> Running transaction check
---> Package libwebp.x86_64 0:0.3.0-3.5.amzn1 will be installed
---> Package libxml2-python27.x86_64 0:2.9.1-6.3.49.amzn1 will be installed
--> Processing Dependency: libxml2 = 2.9.1-6.3.49.amzn1 for package: libxml2-python27-2.9.1-6.3.49.amzn1.x86_64
---> Package libzip.x86_64 0:0.10.1-1.3.amzn1 will be installed
---> Package python27-kitchen.noarch 0:1.1.1-5.6.amzn1 will be installed
--> Processing Dependency: python27-chardet for package: python27-kitchen-1.1.1-5.6.amzn1.noarch
---> Package tcl.x86_64 1:8.5.7-6.9.amzn1 will be installed
--> Running transaction check
---> Package libxml2.i686 0:2.9.1-6.3.49.amzn1 will be installed
--> Processing Dependency: libc.so.6 for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libdl.so.2(GLIBC_2.0) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: liblzma.so.5 for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libdl.so.2 for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libc.so.6(GLIBC_2.3) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libc.so.6(GLIBC_2.3.2) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libc.so.6(GLIBC_2.2) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libm.so.6(GLIBC_2.1) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libc.so.6(GLIBC_2.15) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: liblzma.so.5(XZ_5.0) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libc.so.6(GLIBC_2.1.3) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libz.so.1(ZLIB_1.2.3.3) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libz.so.1 for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libm.so.6 for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libc.so.6(GLIBC_2.1) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libdl.so.2(GLIBC_2.1) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libc.so.6(GLIBC_2.7) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libc.so.6(GLIBC_2.0) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libc.so.6(GLIBC_2.3.4) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libm.so.6(GLIBC_2.0) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libc.so.6(GLIBC_2.4) for package: libxml2-2.9.1-6.3.49.amzn1.i686
--> Processing Dependency: libz.so.1(ZLIB_1.2.2.3) for package: libxml2-2.9.1-6.3.49.amzn1.i686
---> Package python27-chardet.noarch 0:2.0.1-7.7.amzn1 will be installed
--> Running transaction check
---> Package glibc.i686 0:2.17-196.172.amzn1 will be installed
--> Processing Dependency: glibc-common = 2.17-196.172.amzn1 for package: glibc-2.17-196.172.amzn1.i686
--> Processing Dependency: nss-softokn-freebl(x86-32) >= 3.16.2.3 for package: glibc-2.17-196.172.amzn1.i686
--> Processing Dependency: libgcc(x86-32) for package: glibc-2.17-196.172.amzn1.i686
--> Processing Dependency: libfreebl3.so(NSSRAWHASH_3.12.3) for package: glibc-2.17-196.172.amzn1.i686
--> Processing Dependency: libfreebl3.so for package: glibc-2.17-196.172.amzn1.i686
---> Package xz-libs.i686 0:5.1.2-12alpha.12.amzn1 will be installed
---> Package zlib.i686 0:1.2.8-7.18.amzn1 will be installed
--> Running transaction check
---> Package glibc.i686 0:2.17-196.172.amzn1 will be installed
--> Processing Dependency: glibc-common = 2.17-196.172.amzn1 for package: glibc-2.17-196.172.amzn1.i686
---> Package libgcc48.i686 0:4.8.3-9.111.amzn1 will be installed
---> Package nss-softokn-freebl.i686 0:3.16.2.3-14.4.39.amzn1 will be installed
--> Finished Dependency Resolution
Error: Package: glibc-2.17-196.172.amzn1.i686 (amzn-updates)
           Requires: glibc-common = 2.17-196.172.amzn1
           Installed: glibc-common-2.17-260.175.amzn1.x86_64 (@amzn-updates/latest)
               glibc-common = 2.17-260.175.amzn1
           Available: glibc-common-2.17-157.169.amzn1.x86_64 (amzn-main)
               glibc-common = 2.17-157.169.amzn1
           Available: glibc-common-2.17-157.170.amzn1.x86_64 (amzn-updates)
               glibc-common = 2.17-157.170.amzn1
           Available: glibc-common-2.17-196.172.amzn1.x86_64 (amzn-updates)
               glibc-common = 2.17-196.172.amzn1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
The command '/bin/sh -c yum -y update && yum makecache fast && yum -y install tar xz yum-utils gcc gcc-c++ make autoconf aclocal automake libtool findutils libjpeg-devel libpng-devel libtiff-devel zlib-devel libzip-devel freetype-devel lcms2-devel libwebp-devel tcl-devel tk-devel wget tar diffutils autoconf automake libjpeg8-devel libtiff5-devel zlib1g-devel zip' returned a non-zero code: 1
`

**Comment by gwittchen** [comment]
Hey,

Thanks for you feedback. I think the `yum-utils` can be safely removed.
I will update the dockerfile.

**Comment by gwittchen** [comment]
fixed https://github.com/gwittchen/lambda-ocr/pull/7
